name: "CI"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: drakona/php:7.4-ci
    services:
      db: 
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: adopte-un-chien

    steps:
      - uses: actions/checkout@v2
      - run: cp .env.ci .env
      - run: composer install
      - run: php bin/console doctrine:migrations:migrate -n
      - run: php bin/console doctrine:fixtures:load -n